
class ArabicStrings {
    

    static var ArabicStringsDictionary = [
        "MainLbl":"توصيل البضائع الخاصة بك اينما كنت",
        "signInBtnMain":"دخول",
        "signIn_Validation":"من فضلك ادخل الايميل او كلمة المرور!",
        "registerBtnMain":"تسجيل",
        "register_Validation":"من فضلك تحقق من الايميل او الحقول الاخري",
        "registerLbl":"تسجيل العميل",
        "mobileTxt":"     رقم الجوال",
        "passwordTxt":"     رقم المرور ",
        "emailTxt":"     البريد الإلكتروني",
        "nameTxt":"     الأسم",
        "userNameTxt":"   اسم المستخدم",
        "registerationBtn":"سجل الآن",
        "emailSigInVC":"رقم الجوال",
        "passworfSignInVC":"     رقم المرور ",
        "signInLbl":"تسجيل الدخول",
        "SignInBtn":"تسجيل الدخول",
        "RegisterBtn":"جديد هنا ؟ سجل الأن",
        "ForgetBtn":"نسيت كلمة المرور",
        "forgetLbl":" نسيت كلمة المرور",
        "emailTxtForget":"البريد الإلكترونى",
        "sendforgetBtn":"ارسال",
        "please_wait":"برجاء الانتظار...",
        "AlertTitle":"تنبيه",
        "AlertMessage":"تم التسجيل بنجاح",
        "editAlertTitle":"تنبيه",
        "editAlertMessage":"تم تحديث الملف الشخصي بنجاح",
        "ok":"موافق",
        "cancel":"الغاء",
        "forgetAlert":"تنبيه",
        "forgetAlertMessage":"تفقد بريدك الالكتروني من فضلك",
        "paramCheck":"من فضلك ادخل جميع البيانات",
        "noDriverFound":"لا يوجد سائقين",
        "noDriverAccept":"لم يتم الوافقة علي طلبك",
        "driverAccept":"تم قبول طلبك",
        "driverSuggest":"هناك اقتراحات",
        "loadingLbl":"من فضلك انتظر...",
        "search_places":"ابحث عن مكان",
        "type_msg":"اكتب رسالة",
        "fees":"التكلفة",
        "sar":"ريال",
        "from":"من",
        "to":"الى",
        "sent_to":"مرسل ل",
        "TripAlert":"تنبيه",
        "TripMessage":"هل تريد الغاء الرحلة",
        "trip_completed":"الرحلة انتهت",
        "fees_smaller_than_ten":"التكلفة اصغر من عشرة ريال",
        "imageAlertTitle":"اختر صورة",
        "camera":"كاميرا",
        "Photo Library":"مكتبة الصور",
        "imageAlertCancel":"الغاء",
        "rattingAlert":"من فضلك ضع تقييم اولا",
        "fullName_Setting":"الاسم الكامل",
        "phoneNumber_Setting":"رقم الهاتف",
        "email_Setting":"البريد الإلكتروني",
        "language_Setting":"اللغة",
        "editBtn_Setting":"تعديل",
        "signOutBtn_Setting":"تسجيل خروج",
        "fullName_edit":"الاسم الكامل",
        "phoneNumber_edit":"رقم الهاتف",
        "email_edit":"البريد الإلكتروني",
        "oldPassword_edit":"كلمة المرور القديمة",
        "newPassword_edit":"كلمة مرور جديدة",
        "submit_edit":"ارسال",
        "close_edit":"الغاء",
        "cashOnDelicer_Btn":"الدفع عند الاستلام",
        "creditCard_Btn":"بطاقة إئتمان",
        "redeemVoucher_Btn":"استبدال القسيمة",
        "creditLbl":"ائتمان",
        "use_Credit":"استخدام بطاقة الائتمان",
        "transactionLbl":"كل المعاملات هي عبر اتصالات آمنة عبر SSL",
        "segmentedOpen":"مفتوح",
        "segmentedExcuted":"منفذ",
        "segmentedClose":"أنهى",
        "reciverName_Delivery":"اسم المرسل اليه",
        "phone_Delivery":"رقم الهاتف",
        "fees_Delivery":"سعرك المقترح للتوصيل",
        "description_Delivery":"مواصفات",
        "submit_Delivery":"ارسال",
        "categoryLbl_Bring":"الاقسام",
        "customCategory_Bring":"قسم مخصص",
        "recommendedPlace_Bring":"الاماكن المقترحة",
        "feesLbl_Bring":"السعر المقترح",
        "submit_Bring":"ارسال",
        "descrip_Bring":"مواصفات",
        "Date_Ratting":"تاريخ",
        "Fees_Ratting":"رسوم",
        "AddComment_Ratting":"اترك تعليق",
        "Submit_Ratting":"ارسال",
        "tripInfo_Info":"معلومات الرحلة",
        "FromInfo_Info":"من",
        "ToInfo_Info":"الى",
        "feesInfo_Info":"رسوم",
        "driverInfo_info":"معلومات السائق",
        "home_tab":"الرئيسية",
        "myOrder_tab":"طلباتي",
        "wallet_tab":"محفظتي",
        "Setting_tab":"اعدادات",
        "language":"تغيير اللغة",
        "change_language_confirm":"هل تريد تغيير اللغة الى الانجليزية؟",
        "englishBtn":"الانجليزية",
        "arabicBtn":"العربية",
        "categoryCustom":"اختر",
        "logOutTitle":"تنبيه",
        "logOutMsg":"هل تريد تسجيل الخروج",
        "DeliveryinActive":"deliver_inactive_ar",
        "DeliveryAcitve":"deliver_active_ar",
        "BringinActive":"bring_inactive_ar",
        "BringActive":"bring_active_ar",
        "BringAlert":"من فضلك ادخل العنوان ",
        "mins":"دقيقة",
        "promo_code":"رمز ترويجي",
        "add_promotion_code":"ضع الرمز الترويجي",
        "add":"اضف",
        "enter_promo":"ادخل الرمز الترويجي اولا",
        "promo_added":"تم اضافة الرمز الترويجي بنجاح",
        "missing_sentence":"اذالم تصلك رسالة التفعيل الحساب اظغط",
        "activation_Btn":"تفعيل حساب",
        "activation_sentence":"ادخل رمز التفعيل هنا",
        "ActiveMassage":"تم التفعيل بنجاح",
        "resendMassage":"تم ارسال الرسالة بنجاح",
        "code_Validation":"من فضلك ادخل كود التفعيل",
        

    ]
}
