
class EnglishStrings {
    
    static var EnglishStringsDictionary = [
        "MainLbl":"Deliver your goods on demand to wherever you are!",
        "signInBtnMain":"Sign In",
        "registerBtnMain":"Register",
        "signIn_Validation":"Please enter your email or password",
        "register_Validation":"Please Check email Field or other Fields",
        "registerLbl":"Customer registration",
        "mobileTxt":"     Mobile Number",
        "passwordTxt":"     Password ",
        "emailTxt":"     Email",
        "nameTxt":"     Name",
        "userNameTxt":"   User Name",
        "registerationBtn":"Register Now",
        "emailSigInVC":"Mobile Number",
        "passworfSignInVC":"     Password",
        "signInLbl":"Sign In",
        "SignInBtn":"Sign In",
        "RegisterBtn":"New here ? Sign Up",
        "ForgetBtn":"Forget Password",
        "forgetLbl":" Forget Password",
        "emailTxtForget":"     Email",
        "sendforgetBtn":"Send",
        "please_wait":"Please Wait...",
        "AlertTitle":"Alert",
        "AlertMessage":"Registeration sucessfully",
        "editAlertTitle":"Alert",
        "editAlertMessage":"profile updated successfully",
        "ok":"OK",
        "cancel":"Cancel",
        "forgetAlert":"Alert",
        "forgetAlertMessage":"Please check your email",
        "paramCheck":"Please enter All Data",
        "noDriverFound":"No Driver Found",
        "noDriverAccept":"No Driver Accept",
        "driverAccept":"Your Order has been Accepted",
        "driverSuggest":"There is Suggestions",
        "loadingLbl":"Please Wait...",
        "search_places":"Search for places",
        "type_msg":"Type message",
        "fees":"Fees",
        "sar":"SR",
        "from":"From",
        "to":"To",
        "sent_to":"Sent To",
        "TripAlert":"Alert",
        "TripMessage":"Do you want to cancel the trip",
        "trip_completed":"Your trip is completed",
        "fees_smaller_than_ten":"Fees is smaller than ten SAR",
        "imageAlertTitle":"Select Image",
        "camera":"Camera",
        "Photo Library":"Photo Library",
        "imageAlertCancel":"Cancel",
        "rattingAlert":"Please put rate First!",
        "fullName_Setting":"Full Name",
        "phoneNumber_Setting":"Phone Number",
        "email_Setting":"Email",
        "language_Setting":"Language",
        "editBtn_Setting":"Edit Profile",
        "signOutBtn_Setting":"Sign Out",
        "fullName_edit":"Full Name",
        "phoneNumber_edit":"Phone Number",
        "email_edit":"Email",
        "oldPassword_edit":"Old Password",
        "newPassword_edit":"New Password",
        "submit_edit":"Send",
        "close_edit":"Cancel",
        "cashOnDelicer_Btn":"Cash on deliver",
        "creditCard_Btn":"Credit Card",
        "redeemVoucher_Btn":"Redeem Voucher",
        "creditLbl":"Credit",
        "use_Credit":"Use credit first",
        "transactionLbl":"All transaction are over secure connections via SSL",
        "segmentedOpen":"Open",
        "segmentedExcuted":"Executed",
        "segmentedClose":"Close",
        "reciverName_Delivery":"Receiver name",
        "phone_Delivery":"Phone",
        "fees_Delivery":"Suggested Price",
        "description_Delivery":"Description",
        "submit_Delivery":"Submit",
        "categoryLbl_Bring":"Category",
        "customCategory_Bring":"Custom Category",
        "recommendedPlace_Bring":"Recommended Place",
        "feesLbl_Bring":"Suggested Price",
        "submit_Bring":"Submit",
        "descrip_Bring":"Description",
        "Date_Ratting":"Date",
        "Fees_Ratting":"Fees",
        "AddComment_Ratting":"Add a Comment",
        "Submit_Ratting":"Submit",
        "tripInfo_Info":"Trip Info",
        "FromInfo_Info":"From",
        "ToInfo_Info":"To",
        "feesInfo_Info":"Fees",
        "driverInfo_info":"Deriver Info",
        "home_tab":"Home",
        "myOrder_tab":"My Order",
        "wallet_tab":"Wallet",
        "Setting_tab":"Settings",
        "change_language_confirm":"Are you sure you want to change language to Arabic?",
        "language":"Change Language",
        "englishBtn":"English",
        "arabicBtn":"Arabic",
        "categoryCustom":"Select Category",
        "logOutTitle":"Alert",
        "logOutMsg":"Do you want to SignOut",
        "DeliveryinActive":"deliver_inactive-1",
        "DeliveryAcitve":"deliver_active-1",
        "BringinActive":"bring_inactive",
        "BringActive":"bring_active",
        "mins":"Mins",
        "promo_code":"Promo Code",
        "add_promotion_code":"Add your promo code here",
        "add":"ADD",
        "BringAlert":"please enter address !",
        "enter_promo":"Enter Promotion Code First",
        "promo_added":"Promotion code is added to your wallet successfully",
        "activation_sentence":"Enter the activation code",
        "missing_sentence":"If you do not receive activation key click",
        "activation_Btn":"Activate account",
        "ActiveMassage":"active successfully",
        "resendMassage":"Message has been sent",
        "code_Validation":"Please enter activation code"



    ]
}
